# Generated by Django 5.2.6 on 2025-09-06 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nurej', models.CharField(max_length=50, unique=True, verbose_name='NUREJ')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula de Identidad')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Cliente')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('tipo_proceso', models.CharField(max_length=100, verbose_name='Tipo de Proceso')),
                ('juzgado', models.CharField(max_length=200, verbose_name='Juzgado')),
                ('honorarios_pactados', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Honorarios Pactados')),
                ('pago_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pago Inicial')),
                ('ultima_actuacion', models.TextField(blank=True, verbose_name='Última Actuación')),
                ('fecha_ultima_actuacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Última Actuación')),
                ('proxima_actuacion', models.TextField(blank=True, verbose_name='Próxima Actuación')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('CONCLUIDO', 'Concluido'), ('ABANDONADO', 'Abandonado')], default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Audiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.TextField(verbose_name='Detalle de la Audiencia')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiencias', to='gestion.cliente')),
            ],
            options={
                'verbose_name': 'Audiencia',
                'verbose_name_plural': 'Audiencias',
                'ordering': ['fecha', 'hora'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Documento')),
                ('archivo', models.FileField(upload_to='documentos/', verbose_name='Archivo')),
                ('tipo', models.CharField(choices=[('JPG', 'Imagen JPG'), ('DOCX', 'Documento Word'), ('XLSX', 'Hoja de Cálculo'), ('PDF', 'Documento PDF')], max_length=10, verbose_name='Tipo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='gestion.cliente')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('fecha', models.DateField(verbose_name='Fecha de Pago')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='gestion.cliente')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TAREA', 'Tarea'), ('EVENTO', 'Evento Importante'), ('AUDIENCIA', 'Audiencia'), ('REVISION', 'Revisión de Expediente')], max_length=20, verbose_name='Tipo de Actividad')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(blank=True, null=True, verbose_name='Hora')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='gestion.cliente')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'ordering': ['fecha', 'hora'],
            },
        ),
    ]
