# Generated by Django 5.2.6 on 2025-09-19 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_pago_options_remove_pago_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='concepto',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='metodo_pago',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='observaciones',
        ),
    ]
