# Generated by Django 5.2.6 on 2025-09-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_pago_options_pago_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='LEXNOVA & ASOCIADOS', max_length=200)),
                ('direccion', models.CharField(default='Av. [Nombre de la avenida] N° [XXX], Piso [X], La Paz – Bolivia', max_length=300)),
                ('telefono', models.CharField(default='(+591) [Número]', max_length=100)),
                ('email', models.EmailField(default='contacto@lexnova.bo', max_length=254)),
            ],
            options={
                'verbose_name': 'Configuración de Empresa',
                'verbose_name_plural': 'Configuración de Empresa',
            },
        ),
    ]
