# Generated by Django 5.2.6 on 2025-09-20 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_configuracionempresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puede_gestionar_clientes', models.BooleanField(default=False)),
                ('puede_gestionar_agenda', models.BooleanField(default=False)),
                ('puede_gestionar_pagos', models.BooleanField(default=False)),
                ('puede_gestionar_documentos', models.BooleanField(default=False)),
                ('puede_crear_usuarios', models.BooleanField(default=False)),
                ('puede_modificar_config', models.BooleanField(default=False)),
                ('es_administrador', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
    ]
